### ISSUE TITLE
無駄な周回数が表示される場合がある

### ISSUE THREAD

**Issue by kanata3249** [antenna-three/fgo-farming-solver-api#1]
以下の周回数計算にて、山裾の密林427周ですべて集まっているが、
公会堂1周も必要と表示されている。

https://fgo-farming-solver.vercel.app/results/8f089e23-22f1-43f7-a411-422fdbc4d5cb

**Comment by antenna-three** [comment]
このプログラムはクエスト周回数を整数ではなく実数として線形計画を解いているので、ソルバーから出力される周回数は実数となっています。
レスポンスとして出される周回数はこれを切り上げたものになっているため、足りない羽根の端数を埋めるために公会堂を端数周回する結果になり、公会堂周回数の端数が切り上げられて1周が出力されたものと思われます。

解決策として、

1. 周回数の丸めを切り上げから四捨五入に変更する。ただし、例えば骨1本を集めるのに冬木X-G（骨のドロップ率70%）を1周すればよいといった結果になる。
2. 周回数の丸めを切り上げから0-0.5のしきい値を持つステップ関数に変更する。しきい値の妥当性の評価が難しい。
3. 周回数が1周になっているものを整数変数として混合整数計画問題にする。

といったものがあります。どれも一長一短あるので、現状維持も含め検討します。

**Comment by kanata3249** [comment]
本質的な解決方法ではありませんが、目立つのは1周でドロップ0のものなので、
  最終結果からドロップ1未満のものを除外する
とかでも良いかもと勝手に思いました

特に困っているわけではないので、放置していただいても大丈夫です

**Comment by antenna-three** [comment]
全体の一貫性を考慮して周回数の丸めを四捨五入に変更しました。
